### PR TITLE
standardized getting nodes from map

### PR DESCRIPTION
**Pull request by megawidget**
Does this need unit tests? It seems fairly trivial.

### CODE REVIEW

**Comment by aprocter** [comment]
#82 includes a similar solution for this that also handles the issue of multi-output ops, so I think it'd be best to just go with that.

**Comment by megawidget** [comment]
I suppose if you don't want your outputs named.

**Comment by avijit-nervana** [comment]
Looks like #82 renders this one moot - no?

**Comment by megawidget** [comment]
I suppose so. :(

**Pull request closed without merging**
