### PR TITLE
sarkars/copyright_check

### PR DESCRIPTION
**Pull request by sayantan-nervana**

### CODE REVIEW

**Comment by sayantan-nervana** [comment]
The script is conservative, so it migth have false positives like tf_deadness_analysis

**Comment by sayantan-nervana** [comment]
example file which the script fails:
`https://github.com/NervanaSystems/ngraph-tf/blob/master/test/python/common.py`

need to debug later

**Comment by shresthamalik** [comment]
This script will be really helpful. Thanks @sayantan-nervana 👍

**Comment by sayantan-nervana** [comment]
new output:

```
Possibly no copyright line found: ./src/ngraph_api.cc
Possibly no copyright line found: ./src/tf_deadness_analysis.cc
Possibly no copyright line found: ./src/ngraph_api.h
Possibly no copyright line found: ./src/tf_deadness_analysis.h
Possibly no copyright line found: ./src/tf_graphcycles.h
Possibly no copyright line found: ./src/tf_graphcycles.cc
Possibly no copyright line found: ./examples/mnist/mnist_cnn_inference.py
Possibly no copyright line found: ./examples/mnist/mnist_deep_simplified.py
Possibly no copyright line found: ./examples/mnist/mnist_fprop_only.py
Possibly no copyright line found: ./test/resnet_unit_test.py
Possibly no copyright line found: ./test/python/common.py
Possibly no copyright line found: ./diagnostics/model_test/verify_model.py
```

**Comment by fboemer** [comment]
The failure seems unrelated:
```
        for v, e in zip(slice_vals, expected):
>           np.testing.assert_array_equal(v, e)
E           AssertionError: 
E           Arrays are not equal
E           
E           (shapes (0, 5), (4, 5) mismatch)
E            x: array([], shape=(0, 5), dtype=float32)
E            y: array([[0.005202, 0.711509, 0.47054 , 0.972025, 0.449617],
E                  [0.029762, 0.312242, 0.009409, 0.92572 , 0.387757],
E                  [0.779166, 0.705877, 0.663553, 0.282641, 0.400346],
E                  [0.223329, 0.150659, 0.951321, 0.948918, 0.264032]], dtype=float32)

test_slice.py:152: AssertionError
=============== 1 failed, 79 passed, 51 skipped in 4.38 seconds ================
```

**Pull request closed without merging**
