### PR TITLE
Modify Mac builds to use TensorFlow 1.12.0 for builds

### PR DESCRIPTION
**Pull request by crlishka**
Mac builds were still using "tensorflow==1.12.0rc2" for builds.  This PR updates them to use "tensorflow==1.12.0".

Successful testing: 
https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-tf-mac-daily-build/86/

### CODE REVIEW

**Comment by avijit-nervana** [comment]
BTW - all builds should use TF1.12.0 (and not the rc2)

**Comment by crlishka** [comment]
TESTNOW

**Comment by crlishka** [comment]
> BTW - all builds should use TF1.12.0 (and not the rc2)

Agreed.  This is one that I forgot to update (probably right before I went on vacation).

Ideally, in the future, we can just use "pip install tensorflow", without any version number.  But for now we will lock the version.

**Comment by crlishka** [comment]
Previous CI job ended up on a node, hung.  Checked with Nick, job should not have hung, he rebooted the node.  I am resubmitting the CI job.

**Comment by crlishka** [comment]
TESTNOW

**Pull request merged**
