### PR TITLE
Implement ngraph.set_backend()

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by earhart** [comment]
Actually -- hold off on reviewing this a sec?  I'm going to squash and rebase to get rid of all of those merge commits.  (Why do we have merge commits, anyway?  :-)

**Comment by sayantan-nervana** [comment]
> Actually -- hold off on reviewing this a sec? I'm going to squash and rebase to get rid of all of those merge commits. (Why do we have merge commits, anyway? :-)

Oh, ok. Seeing your comment now. Already did a master merge though :(. but feel free to reset head and do what ever you want, and then let us know when its ready.

**Comment by earhart** [comment]
It should be good to go, except that ci appears to have failed -- I'm digging into it now.

**Comment by earhart** [comment]
I don't understand the ngraph-tf Jenkins config well enough to see what's going wrong.  :-/. But it looks to me like ngraph-tf-unittest has been failing reliably since this afternoon.  This change builds fine on my local machine...

**Comment by crlishka** [comment]
TESTNOW

**Pull request closed without merging**
